language: python

service:
  - mysql

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install python3-dev; fi

before_script:
  - pip install -U docutils pygments
  - mysql -uroot -e 'grant all on *.* to "osc"@"localhost" identified by "osc"'
  - mysql -uroot -e 'create database if not exists test'
  - echo -e "[server]\nsocket=/tmp/mysql.sock" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - sudo chmod 777 -R /var/lib/mysql

install:
  - python3 setup.py install 

script:
   # bug in distutils prevents check -r -s passing, Python 3.3 on Travis is too old to include the fix:
   # https://github.com/travis-ci/travis-ci/issues/7028#issuecomment-267115326
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then python3 setup.py check -r -s; fi
  - cd $TRAVIS_BUILD_DIR && ./test_cli --mysql-user=osc --mysql-password=osc --database test --socket=/tmp/mysql.sock 
